### ISSUE TITLE
Wouldn't an AppImage be a better format for the Linux release?

### ISSUE THREAD

**Issue by rzel** [TiddlyWiki/TiddlyDesktop#231]
It's like a portable .exe on Windows or a portable .app file on Mac. 

VERY popular on Linux right now and runs on all the distros without installation, from a single self-contained file. Much better than a messy folder of files and other folders which is hard to find the "nw" file efficiently. 

Thanks for all your work
Rob

**Comment by Jermolene** [comment]
Thanks @rzel AppImage is new to me, but looks like a great solution.

**Comment by rzel** [comment]
Here is a huge list of some of the biggest Linux apps using AppImage format. 

https://appimage.github.io/apps/

Two on the list that I currently use are Inkscape and Electrum. 

Are there any plans for an installable ppa?

If not, AppImage is the way to go.

**Comment by Jermolene** [comment]
Hi @rzel I'm not a Linux user myself, so this is an area where I could do with some help. The underlying nw.js framework that we use in TiddlyDesktop is reasonably popular, and I've found some references to people packaging nw.js apps for AppImage, so with any luck somebody else has already done everything that we need to do. Would you be interested in helping?

**Comment by rzel** [comment]
Alright, I'll try it. 

You've done a lot, the TiddlyWiki inventor did a lot, so I will try to contribute something back for you guys. 

If I get this thing working though, I would like a download link where people can see it easily.

**Comment by Jermolene** [comment]
> Alright, I'll try it.

Thanks @rzel 

> You've done a lot, the TiddlyWiki inventor did a lot, so I will try to contribute something back for you guys.

That's me, too!
 
> If I get this thing working though, I would like a download link where people can see it easily.

A download link for the AppImage? Where are they normally distributed?

**Comment by rzel** [comment]
I just meant a download link on the tiddlywiki page or this github where people can easily find it.

**Comment by emmanuelrosa** [comment]
I did some research on this, and the blocker at this time is that the squashfs tools don't run on MacOS. Squashfs is the filesystem used by AppImage. It's going to be challenging for the maintainer to build AppImages if the tool needed requires Linux.

An alternative is to use Arx (https://github.com/solidsnack/arx). Arx is a tool which bundles an archive with a shell script, to create a "self-executing" bundle.

They both provide the same user-experience:

- Download the program.
- Set the execute bit: `chmod u+x TiddlyDesktop.sh`
- Run the program.

Arx is written in Haskell and has few dependencies, thus it's quite likely that it runs on MacOS. My implementation idea is as follows:

- Add MacOS and Linux binaries of Arx to the repo. This way, contributors don't need to install a Haskell toolchain and build Arx.
- Update bld.sh so that it first attempts to find an installed Arx, and fails back to the provided binaries.
- Then the script will use Arx to bundle the Linux versions of Tiddly Desktop.

This would allow the maintainer to provide Linux executables that work like an AppImage.

Would this be a suitable alternative to using AppImage?

**Comment by Jermolene** [comment]
Fixed in #309
