### ISSUE TITLE
Can't translate pathname to UTF-8

### ISSUE THREAD

**Issue by jeancf** [TiddlyWiki/TiddlyDesktop#278]
Hi,

I am packaging Tiddlydesktop for the Archlinux distribution (https://aur.archlinux.org/packages/tiddlydesktop). No biggie, but the packaging script `makepkg` issues the following warning:

```
: Can't translate pathname 'usr/share/tiddlydesktop/tiddlywiki/editions/fr-FR/tiddlers/community/editions/_Noteself_ by Danielo Rodríguez.tid' to UTF-8
```

And the file is not included in the package as a result.

**Comment by rmunn** [comment]
That seems odd, because [that file in the TiddlyWiki5 repo](https://github.com/tw-FRed/TiddlyWiki5/blob/5de89d008c1c8ebb81eb4ffca6b37738b643b79c/editions/fr-FR/tiddlers/community/editions/_Noteself_%20by%20Danielo%20Rodr%C3%ADguez.tid) has a pathname that's already in UTF-8. Paste the name Rodríguez into `xxd` and you'll see that the í is 0xc3 0xad, which is correct UTF-8 encoding for U+00ED LATIN SMALL LETTER I WITH ACUTE. I just downloaded the linux64 zip file from https://github.com/TiddlyWiki/TiddlyDesktop/releases/tag/v0.0.18 and it also unzips with the filename already in UTF-8. So this error message seems odd, as there shouldn't be any problems translating a filename into UTF-8 that was already in UTF-8.

Do you still get this error if you run the makepkg step again? Perhaps something changed in the past four months.

**Comment by jeancf** [comment]
The error is still there. But I see that the filename is still correctly encoded in  the `pkg` folder that is used by the tool to create the package. It is at the `Compressing package...` stage of the process that the error appears. So clearly an issue with Archlinux' `makepkg` and not with the contents of the original zip file.
